name: CD

on:
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.release.target_commitish}}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm i -g yarn
          yarn install
          yarn eslint ./src
  build-and-publish:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.release.target_commitish}}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org
      - name: Set cd-bot git configuration
        run: |
          git config --global user.name "cd-bot"
          git config --global user.eamil "bityoungjae@gmail.com"
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build package
        run: |
          npm version ${{github.event.release.tag_name}}
          yarn build
      - name: Publish package to npm
        run :
          npm publish
          git push
        env:
          github-token: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}