# This is a basic workflow to help you get started with Actions

name: CI & CD

# Controls when the workflow will run
on:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.release.target_commitish}}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: |
          npm i -g yarn
          yarn install
          yarn eslint ./src
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.release.target_commitish}}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: https://registry.npmjs.org
      - run: |
          git config --global user.name "BitYoungjae"
          git config --global user.eamil "bityoungjae@gmail.com"
          npm version ${{github.event.release.tag_name}}
          npm i -g yarn
          yarn install --frozen-lockfile
          yarn build
          npm publish
          git push
        env:
          github-token: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
